// Command reset-gen scans the module for structs marked with the
// "generate:reset" doc comment and generates Reset() methods for them
// into reset.gen.go files (one per package).
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	marker      = "generate:reset"
	genSuffix   = ".gen.go"
	outFileName = "reset.gen.go"
	fileHeader  = "// Code generated by go generate; DO NOT EDIT.\n\n"
)

func main() {
	if err := run("."); err != nil {
		fmt.Fprintln(os.Stderr, "reset-gen:", err)
		os.Exit(1)
	}
}

func run(root string) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		switch {
		case err != nil:
			return err
		case !d.IsDir():
			return nil
		case path != root && shouldSkipDir(d.Name()):
			return filepath.SkipDir
		}
		return processDir(path)
	})
}

func shouldSkipDir(name string) bool {
	return strings.HasPrefix(name, ".") ||
		strings.HasPrefix(name, "_") ||
		name == "vendor" ||
		name == "testdata"
}

func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, isSourceFile, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse %s: %w", dir, err)
	}

	for pkgName, pkg := range pkgs {
		structs := collectMarkedStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		src, err := renderFile(pkgName, structs)
		if err != nil {
			return fmt.Errorf("generate for package %s: %w", pkgName, err)
		}

		outPath := filepath.Join(dir, outFileName)
		if err := os.WriteFile(outPath, src, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
	}
	return nil
}

// isSourceFile excludes previously generated files from parsing.
func isSourceFile(fi fs.FileInfo) bool {
	return !strings.HasSuffix(fi.Name(), genSuffix)
}

type markedStruct struct {
	Name string
	Type *ast.StructType
}

// collectMarkedStructs returns structs annotated with the marker,
// in deterministic (file-name) order.
func collectMarkedStructs(pkg *ast.Package) []markedStruct {
	fileNames := make([]string, 0, len(pkg.Files))
	for name := range pkg.Files {
		fileNames = append(fileNames, name)
	}
	sort.Strings(fileNames)

	var structs []markedStruct
	for _, fileName := range fileNames {
		for _, decl := range pkg.Files[fileName].Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if hasMarker(gd.Doc) || hasMarker(ts.Doc) {
					structs = append(structs, markedStruct{Name: ts.Name.Name, Type: st})
				}
			}
		}
	}
	return structs
}

func hasMarker(doc *ast.CommentGroup) bool {
	return doc != nil && strings.Contains(doc.Text(), marker)
}

func renderFile(pkgName string, structs []markedStruct) ([]byte, error) {
	var sb strings.Builder
	sb.WriteString(fileHeader)
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)

	for _, s := range structs {
		writeResetMethod(&sb, s)
	}
	return format.Source([]byte(sb.String()))
}

func writeResetMethod(sb *strings.Builder, s markedStruct) {
	fmt.Fprintf(sb, "func (rs *%s) Reset() {\n", s.Name)
	sb.WriteString("\tif rs == nil {\n\t\treturn\n\t}\n")

	for _, field := range s.Type.Fields.List {
		for _, name := range field.Names {
			writeFieldReset(sb, "rs."+name.Name, field.Type)
		}
	}
	sb.WriteString("}\n\n")
}

func writeFieldReset(sb *strings.Builder, f string, typ ast.Expr) {
	switch t := typ.(type) {
	case *ast.Ident:
		fmt.Fprintf(sb, "\t%s = %s\n", f, zeroValue(t.Name))
	case *ast.ArrayType:
		if t.Len == nil { // slice: truncate, keep capacity
			fmt.Fprintf(sb, "\t%s = %s[:0]\n", f, f)
		}
	case *ast.MapType:
		fmt.Fprintf(sb, "\tclear(%s)\n", f)
	case *ast.StarExpr:
		writePointerReset(sb, f, t)
	}
}

func writePointerReset(sb *strings.Builder, f string, t *ast.StarExpr) {
	id, ok := t.X.(*ast.Ident)
	if !ok {
		return
	}
	if isBasic(id.Name) {
		fmt.Fprintf(sb, "\tif %s != nil {\n\t\t*%s = %s\n\t}\n", f, f, zeroValue(id.Name))
		return
	}
	// Named type: call Reset() if the type provides it.
	fmt.Fprintf(sb,
		"\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\t\tresetter.Reset()\n\t}\n",
		f, f)
}

// zeroValue returns the literal used to reset a basic type.
// Unknown identifiers are assumed numeric (matches original behavior).
func zeroValue(typeName string) string {
	switch typeName {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "0"
	}
}

func isBasic(name string) bool {
	switch name {
	case "string", "bool",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "byte", "rune":
		return true
	}
	return false
}
