package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	err := filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() {
			return err
		}
		return processDir(path)
	})
	if err != nil {
		panic(err)
	}
}

func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), ".gen.go")
	}, parser.ParseComments)
	if err != nil {
		return err
	}

	for pkgName, pkg := range pkgs {
		var sb strings.Builder
		found := false

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts := spec.(*ast.TypeSpec)
					st, ok := ts.Type.(*ast.StructType)
					if !ok || !hasMarker(gd.Doc) && !hasMarker(ts.Doc) {
						continue
					}
					genReset(&sb, ts.Name.Name, st)
					found = true
				}
			}
		}

		if !found {
			continue
		}

		out := "// Code generated by go generate; DO NOT EDIT.\n\npackage " + pkgName + "\n\n" + sb.String()
		formatted, err := format.Source([]byte(out))
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "reset.gen.go"), formatted, 0644); err != nil {
			return err
		}
	}
	return nil
}

func hasMarker(cg *ast.CommentGroup) bool {
	return cg != nil && strings.Contains(cg.Text(), "generate:reset")
}

func genReset(sb *strings.Builder, name string, st *ast.StructType) {
	fmt.Fprintf(sb, "func (rs *%s) Reset() {\n\tif rs == nil {\n\t\treturn\n\t}\n", name)

	for _, field := range st.Fields.List {
		for _, fn := range field.Names {
			f := "rs." + fn.Name

			switch t := field.Type.(type) {
			case *ast.Ident:
				switch t.Name {
				case "string":
					fmt.Fprintf(sb, "\t%s = \"\"\n", f)
				case "bool":
					fmt.Fprintf(sb, "\t%s = false\n", f)
				default:
					fmt.Fprintf(sb, "\t%s = 0\n", f)
				}
			case *ast.ArrayType:
				fmt.Fprintf(sb, "\t%s = %s[:0]\n", f, f)
			case *ast.MapType:
				fmt.Fprintf(sb, "\tclear(%s)\n", f)
			case *ast.StarExpr:
				if id, ok := t.X.(*ast.Ident); ok {
					switch id.Name {
					case "string":
						fmt.Fprintf(sb, "\tif %s != nil {\n\t\t*%s = \"\"\n\t}\n", f, f)
					case "bool":
						fmt.Fprintf(sb, "\tif %s != nil {\n\t\t*%s = false\n\t}\n", f, f)
					case "int", "int8", "int16", "int32", "int64", "uint", "uint8",
						"uint16", "uint32", "uint64", "float32", "float64", "byte", "rune":
						fmt.Fprintf(sb, "\tif %s != nil {\n\t\t*%s = 0\n\t}\n", f, f)
					default:
						fmt.Fprintf(sb, "\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\t\tresetter.Reset()\n\t}\n", f, f)
					}
				}
			}
		}
	}
	fmt.Fprintf(sb, "}\n\n")
}
